const estados = {
  AC: 'ACRE',
  AL: 'ALAGOAS',
  AM: 'AMAZONAS',
  AP: 'AMAPA',
  BA: 'BAHIA',
  CE: 'CEARA',
  DF: 'DISTRITO FEDERAL',
  ES: 'ESPÍRITO SANTO',
  GO: 'GOIAS',
  MA: 'MARANHÃO',
  MT: 'MATO GROSSO',
  MS: 'MATO GROSSO DO SUL',
  MG: 'MINAS GERAIS',
  PA: 'PARÁ',
  PB: 'PARAIBA',
  PR: 'PARANÁ',
  PE: 'PERNAMBUCO',
  PI: 'PIAUÍ',
  RJ: 'RIO DE JANEIRO',
  RN: 'RIO GRANDE DO NORTE',
  RO: 'RONDÔNIA',
  RS: 'RIO GRANDE DO SUL',
  RR: 'RORAIMA',
  SC: 'SANTA CATARINA',
  SE: 'SERGIPE',
  SP: 'SÃO PAULO',
  TO: 'TOCANTINS',
};

export default estados;
