export { default as formatCnpjCpf } from './formatCnpjCpf';
export { default as formatBR } from './formatBR';
export { default as toLocaleDateString } from './toLocaleDateString';
export { default as formatDatePedido } from './formatDatePedido';
export { default as formatCEP } from './formatCEP';
export { default as formatCNPJ } from './formatCNPJ';
export { default as formatCPF } from './formatCPF';
export { default as formatDDDFone } from './formatDDDFone';
export { default as validar } from './validar';
